spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot_learn?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

# 如果想看到mybatis日志需要做如下配置
logging:
  level:
    com:
      kylexu: debugd

######### Mybatis 自身配置 ##########
mybatis:
  mapper-locations: mapper/*.xml
  type-aliases-package: com.kylexu.springbootmapper.mapper
  configuration:
    # 驼峰命名规范 如：数据库字段是  order_id 那么 实体字段就要写成 orderId
    map-underscore-to-camel-case: true

######### 通用Mapper ##########
# 主键自增回写方法,默认值MYSQL,详细说明请看文档
mapper:
  mappers:
  # 第一个是配置通用接口所在的目录
  #  - tk.mybatis.mapper.common.BaseMapper
  - com.kylexu.springbootmapper.utils.CommonMapper
  # 设置 insert 和 update 中，是否判断字符串类型!=''
  not-empty: true
  identity: MYSQL





